Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolProject.Models;
using SchoolProject.Repository;

namespace SchoolProject.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseRepository _icourseRepository;
        private readonly ITeacherRepository _iteacherRepository;

        public CourseController(ICourseRepository icourseRepository,ITeacherRepository teacherRepository)
        {
            _icourseRepository = icourseRepository;
            _iteacherRepository = teacherRepository;
        }

        public ActionResult Index()
        {
            List<Course> courselst = _icourseRepository.GetAllCourses().ToList();
            return View(courselst);
        }
        [HttpGet]
        public ActionResult Create()
        {
            List<Teacher> teacherlst = _iteacherRepository.GetAllTeachers().ToList();
            return View(teacherlst);
        }
        [HttpPost]
        public ActionResult Create(Course course)
        {
            List<Course> courselst = _icourseRepository.GetAllCourses().ToList();
            _icourseRepository.Create(course);
            return View("Index", courselst);
        }
        public ActionResult Delete(int id)
        {
            List<Course> courselst = _icourseRepository.GetAllCourses().ToList();
            _icourseRepository.Delete(id);
            return View("Index", courselst);
        }
    }
}

Controllers/RoomController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolProject.Models;
using SchoolProject.Repository;

namespace SchoolProject.Controllers
{
    public class RoomController : Controller
    {
        private readonly IRoomRepository _iroomRepository;

        public RoomController(IRoomRepository iroomRepository)
        {
            _iroomRepository = iroomRepository;
        }
        [HttpGet]
        public IActionResult Index()
        {
            List<Room> roomlst = _iroomRepository.GetAllRooms().ToList();
            return View(roomlst);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Room room)
        {
            List<Room> roomlst = _iroomRepository.GetAllRooms().ToList();
            _iroomRepository.Create(room);
            return View("Index", roomlst);
        }
        public IActionResult Delete(int id)
        {
            List<Room> roomlst = _iroomRepository.GetAllRooms().ToList();
            _iroomRepository.Delete(id);
            return View("Index", roomlst);
        }
    }
}

Controllers/StudentController.cs
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Core.Types;
using SchoolProject.Models;
using SchoolProject.Models.View_Model;
using SchoolProject.Repository;
using SchoolProject.Models.View_Model;
using System;


namespace SchoolProject.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentRepository _studentRepositoriy;
        private readonly ICourseRepository _courseRepositoriy;
        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment _environment; // Fully qualify the type here




        public StudentController(IStudentRepository studnetRepository , ICourseRepository courseRepositoriy, Microsoft.AspNetCore.Hosting.IHostingEnvironment environment)
        {
            _studentRepositoriy = studnetRepository;
            _courseRepositoriy = courseRepositoriy;
            _environment = environment;

        }

        //to list all the students
        [HttpGet]
        public ActionResult Index()
        {
            List<Student> studentLst = _studentRepositoriy.GetAllStudents();
            return View(studentLst);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Student std , IFormFile formfile)
        {
            if (formfile == null)
            {
                ModelState.AddModelError("formfile", "File is required.");
                return View(); // or return the view with a meaningful message
            }
            var rootPath = _environment.WebRootPath+"/Images/";
            Guid randValue= Guid.NewGuid();
            string fullPath = Path.Combine(rootPath, randValue + "-" + formfile.FileName);
            using var stream = new FileStream (fullPath, FileMode.Create);
            {
                formfile.CopyTo(stream);
            }


            std.StudentPhotoName = randValue + "-" + formfile.FileName;
            List<Student> studentLst = _studentRepositoriy.GetAllStudents();
            _studentRepositoriy.AddStudent(std);
            return View("Index",studentLst);
        }

        public ActionResult Delete(int id)
        {
            _studentRepositoriy.Delete(id);
            List<Student> studentLst = _studentRepositoriy.GetAllStudents();
            return View("Index",studentLst);
        }
        [HttpGet]
        public ActionResult Register()
        {
            List<Student> studentLst = _studentRepositoriy.GetAllStudents();
            List <Course> courseLst = _courseRepositoriy.GetAllCourses();
            StudentsCourses studentsCourses = new StudentsCourses();
            studentsCourses.StudentList = studentLst;
            studentsCourses.CourseList = courseLst;


            return View(studentsCourses);
        }
        [HttpPost]
        public ActionResult Register(int courseId, int studentId)
        {
            _studentRepositoriy.Register(courseId, studentId);
            List<Student> studentLst = _studentRepositoriy.GetAllStudents();
            return View("Index",studentLst);
        }


    }
}

Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolProject.Models;
using SchoolProject.Repository;

namespace SchoolProject.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ITeacherRepository _iteacherRepository;

        public TeacherController(ITeacherRepository iteacherRepository)
        {
            _iteacherRepository = iteacherRepository;
        }

        public ActionResult Index()
        {
            List<Teacher>teacherlst = _iteacherRepository.GetAllTeachers().ToList();
            return View(teacherlst);
        }
        [HttpGet]
        public ActionResult Create() 
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Teacher teacher)
        {
            List<Teacher> teacherlst = _iteacherRepository.GetAllTeachers().ToList();
            _iteacherRepository.Create(teacher);
            return View("Index",teacherlst);
        }
        public ActionResult Delete(int id)
        {
            List<Teacher> teacherlst = _iteacherRepository.GetAllTeachers().ToList();
            _iteacherRepository.Delete(id);
            return View("Index",teacherlst);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SchoolProject</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SchoolProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav>
            <div class="logo">
                <h1>School</h1>
            </div>
            <div class="wrapper">
@*                 <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button> *@
                    <ul class="links">
                        <!--<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Identity" asp-page="Account/Login">Login</a>
                        </li>-->
                        <li class="">
                            <span>
                                <a style="text-decoration:none;color:#000" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </span>
                        </li>
                        <li class="">
                        <span class="link">Students</span>
                            <i class="fa-solid fa-angle-up"></i>
                            <div class="list">
                            <span>
                            <a style="text-decoration:none;color:#fff" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                            </span>
                            <span>
                            <a style="text-decoration:none;color:#fff" asp-area="" asp-controller="Student" asp-action="Create">Create Student</a>
                            </span>
                            </div>
                        </li>
                        <li class="">
                        <span class="link">Teachers</span>
                            <i class="fa-solid fa-angle-up"></i>
                            <div class="list">
                            <span>
                            <a style="text-decoration:none;color:#fff" asp-area="" asp-controller="Teacher" asp-action="Index">Teachers</a>
                            </span>
                            <span>
                            <a style="text-decoration:none;color:#fff" asp-area="" asp-controller="Teacher" asp-action="Create">Create Teacher</a>
                            </span>
                            </div>
                        </li>
                        <li class="">
                        <span class="link">Courses</span>
                            <i class="fa-solid fa-angle-up"></i>
                            <div class="list">
                            <span>
                            <a style="text-decoration:none;color:#fff" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                            </span>
                            <span>
                            <a style="text-decoration:none;color:#fff" asp-area="" asp-controller="Course" asp-action="Create">Create Course</a>
                            </span>
                            </div>
                        </li>
                        <li class="">
                        <span class="link">Rooms</span>
                            <i class="fa-solid fa-angle-up"></i>
                            <div class="list">
                            <span>
                            <a style="text-decoration:none;color:#fff" asp-area="" asp-controller="Room" asp-action="Index">Rooms</a>
                            </span>
                            <span>
                            <a style="text-decoration:none;color:#fff" asp-area="" asp-controller="Room" asp-action="Create">Create Room</a>
                            </span>
                            </div>
                        </li>
                        <li class="">
                            <span>
                                <a style="text-decoration:none;color:#000" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </span>
                        </li>
                    </ul>
            </div>
            <div class="register">
                <a class="btn btn-primary"  asp-area="" asp-controller="Student"asp-action="Register">Registeration</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
        <div class="wrapper bg-black">
        <div class="contain">
            &copy; 2024 - School Platform - <a style="color:#fff" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>